// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartNode(arg1) {
  return window['go']['main']['App']['StartNode'](arg1);
}

export function StopNode() {
  return window['go']['main']['App']['StopNode']();
}
