// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkflow(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14) {
  return window['go']['main']['App']['AddWorkflow'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14);
}

export function AddWorkflowJob(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['main']['App']['AddWorkflowJob'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}

export function AddWorkflowJobInterfacePeer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddWorkflowJobInterfacePeer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CheckAndInstallDependencies() {
  return window['go']['main']['App']['CheckAndInstallDependencies']();
}

export function FindServices(arg1, arg2) {
  return window['go']['main']['App']['FindServices'](arg1, arg2);
}

export function GetServiceCardGUIProps(arg1) {
  return window['go']['main']['App']['GetServiceCardGUIProps'](arg1);
}

export function GetWorkflowGUIProps(arg1) {
  return window['go']['main']['App']['GetWorkflowGUIProps'](arg1);
}

export function GetWorkflowJob(arg1) {
  return window['go']['main']['App']['GetWorkflowJob'](arg1);
}

export function IsHostRunning() {
  return window['go']['main']['App']['IsHostRunning']();
}

export function ListWorkflows(arg1, arg2) {
  return window['go']['main']['App']['ListWorkflows'](arg1, arg2);
}

export function NotifyFrontendReady() {
  return window['go']['main']['App']['NotifyFrontendReady']();
}

export function RemoveWorkflow(arg1) {
  return window['go']['main']['App']['RemoveWorkflow'](arg1);
}

export function RemoveWorkflowJob(arg1) {
  return window['go']['main']['App']['RemoveWorkflowJob'](arg1);
}

export function RemoveWorkflowJobInterfacePeer(arg1, arg2) {
  return window['go']['main']['App']['RemoveWorkflowJobInterfacePeer'](arg1, arg2);
}

export function SetServiceCardGUIProps(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetServiceCardGUIProps'](arg1, arg2, arg3);
}

export function SetUserConfirmation(arg1) {
  return window['go']['main']['App']['SetUserConfirmation'](arg1);
}

export function SetWorkflowGUIProps(arg1, arg2) {
  return window['go']['main']['App']['SetWorkflowGUIProps'](arg1, arg2);
}

export function StartNode(arg1) {
  return window['go']['main']['App']['StartNode'](arg1);
}

export function StopNode() {
  return window['go']['main']['App']['StopNode']();
}

export function UpdateWorkflow(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateWorkflow'](arg1, arg2, arg3);
}
