// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddWorkflow(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string):Promise<main.AddWorkflowResponse>;

export function AddWorkflowJob(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string):Promise<main.AddWorkflowJobResponse>;

export function CheckAndInstallDependencies():Promise<void>;

export function FindServices(arg1:string,arg2:string):Promise<void>;

export function IsHostRunning():Promise<boolean>;

export function NotifyFrontendReady():Promise<void>;

export function RemoveWorkflow(arg1:number):Promise<void>;

export function RemoveWorkflowJob(arg1:number):Promise<void>;

export function SetUserConfirmation(arg1:boolean):Promise<void>;

export function StartNode(arg1:number):Promise<void>;

export function StopNode():Promise<void>;

export function UpdateWorkflow(arg1:number,arg2:string,arg3:string):Promise<void>;
