// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndInstallDependencies() {
  return window['go']['main']['App']['CheckAndInstallDependencies']();
}

export function FindServices(arg1, arg2) {
  return window['go']['main']['App']['FindServices'](arg1, arg2);
}

export function IsHostRunning() {
  return window['go']['main']['App']['IsHostRunning']();
}

export function NotifyFrontendReady() {
  return window['go']['main']['App']['NotifyFrontendReady']();
}

export function SetUserConfirmation(arg1) {
  return window['go']['main']['App']['SetUserConfirmation'](arg1);
}

export function StartNode(arg1) {
  return window['go']['main']['App']['StartNode'](arg1);
}

export function StopNode() {
  return window['go']['main']['App']['StopNode']();
}
