// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndInstallDependencies():Promise<void>;

export function IsHostRunning():Promise<boolean>;

export function StartNode(arg1:number):Promise<void>;

export function StopNode():Promise<void>;
